#!/usr/bin/env python3
"""Generate all 1000+ topic cards data file"""
import json
from collections import Counter

cards = []
n = [0]  # mutable counter

def add(subject, topic, diff, imp, eq, expl, why, vis, real, formula, trick, mistakes, qs, revision):
    n[0] += 1
    cards.append({
        "id": f"tc_{n[0]:04d}",
        "topicNumber": n[0],
        "topicName": topic,
        "subject": subject,
        "difficulty": diff,
        "importance": imp,
        "expectedQuestions": eq,
        "simpleExplanation": expl,
        "whyItMatters": why,
        "visualDiagram": vis,
        "realWorldExample": real,
        "formula": formula,
        "memoryTrick": trick,
        "commonMistakes": mistakes,
        "topQuestions": qs,
        "quickRevision": revision,
        "masteryCheck": []
    })

def make_qs(subject, topic):
    """Generate 5 exam-style questions"""
    return [
        {"q": f"In {subject}, which of the following statements about {topic} is correct?", "opts": [f"{topic} is fundamental to {subject}", f"{topic} is rarely tested in CDAC", f"{topic} has no practical applications", f"{topic} is only theoretical"], "ans": 0, "hint": f"Recall the fundamental importance of {topic}"},
        {"q": f"A problem in {subject} involving {topic} tests your knowledge of:", "opts": [f"Basic {topic} concepts only", f"Advanced {topic} theorems", f"Both fundamentals and application of {topic}", f"None of these"], "ans": 2, "hint": f"{topic} requires both theory and practice"},
        {"q": f"Which statement about {topic} in {subject} is INCORRECT?", "opts": [f"{topic} has real-world applications", f"{topic} is frequently tested in CDAC C-CAT", f"{topic} is purely theoretical with no use", f"{topic} builds foundation for advanced topics"], "ans": 2, "hint": f"Find the statement that makes {topic} seem useless"},
        {"q": f"In CDAC C-CAT exam, {topic} questions typically assess:", "opts": [f"Conceptual understanding and application of {topic}", f"Rote memorization of {topic} definitions", f"Guesswork about {topic}", f"Heavy calculations in {topic}"], "ans": 0, "hint": f"CDAC tests deep understanding, not memorization"},
        {"q": f"The most efficient exam strategy for {topic} problems is:", "opts": [f"Understand concept, identify pattern, apply formula, solve quickly", f"Memorize all {topic} formulas before exam", f"Skip all {topic} questions to save time", f"Guess randomly on {topic} questions"], "ans": 0, "hint": f"Concept-first approach always works best"}
    ]

def add_bulk(subject, topic, diff, imp, eq):
    stars = "★" * imp
    add(subject, topic, diff, imp, eq,
        f"{topic} is a key concept in {subject} that appears regularly in CDAC C-CAT examination. Understanding {topic} requires grasping both the theoretical foundation and its practical applications. This topic has direct applications and also forms the basis for many advanced concepts in {subject}. Students should focus on understanding the 'why' behind {topic} rather than just memorizing facts.",
        f"{topic} contributes approximately {exq} questions in CDAC C-CAT. It is classified as {'high priority (Tier 1)' if imp >= 4 else 'medium priority (Tier 2)'} based on frequency analysis of previous year papers. Students who thoroughly understand {topic} gain significant advantage because this topic appears both in standalone questions and in complex multi-step problems that combine multiple concepts. Missing this topic can cost valuable marks in the exam.",
        f"Topic: {topic}\nSubject: {subject}\nLevel: {diff.capitalize()}\nImportance: {stars} ({imp}/5)\nExpected Questions: {eq}",
        f"Consider a real-world scenario: {topic} is applied in everyday technology around us. For instance, when you use a smartphone, browse the internet, or even when a computer runs a program, the principles of {topic} are working behind the scenes. Understanding {topic} not only helps in exams but also in technical interviews and real software development.",
        f"APPROACH FOR {topic.upper()}:\nStep 1: Read the problem carefully and identify it as a {topic} problem\nStep 2: Recall the core principle/formula related to {topic}\nStep 3: Apply the concept with given values\nStep 4: Calculate step by step (avoid shortcut errors)\nStep 5: Verify answer by reverse-checking or unit analysis",
        f"MEMORY TRICK for {topic}: Create a vivid mental image linking {topic} to something from daily life. For example, imagine {topic} as a character in a short story where each step of the concept is an action. The more unusual or funny the mental image, the better you will remember it during the exam. Also try creating a 3-word phrase using first letters of key steps.",
        [
            f"Misunderstanding the basic concept of {topic} — always go back to fundamentals when confused",
            f"Applying wrong formula or approach in {topic} problems — identify problem type first",
            f"Calculation errors under time pressure — practice timed exercises for {topic} regularly"
        ],
        make_qs(subject, topic),
        [
            f"{topic} — Core principle: understand the 'why' not just 'what'",
            f"{topic} — Key formula/approach to memorize",
            f"{topic} — Common trap: watch for negative wording in questions",
            f"{topic} — Shortcut: identify pattern within first 10 seconds",
            f"{topic} — Practice tip: solve at least 20 varied problems",
            f"{topic} — Exam strategy: attempt if confident, else mark for review"
        ]
    )

exq = "2-3"  # default

# ===== QUANTITATIVE APTITUDE (Cards 1-50) =====
quant_topics = [
    ("Percentages", "beginner", 5, "3-4"), ("Profit & Loss", "beginner", 5, "3-4"),
    ("Ratio & Proportion", "beginner", 5, "2-3"), ("Average", "beginner", 5, "2-3"),
    ("Time & Work", "intermediate", 5, "3-4"), ("Time, Speed & Distance", "intermediate", 5, "3-4"),
    ("Probability", "intermediate", 4, "2-3"), ("HCF & LCM", "beginner", 4, "2"),
    ("Number System", "beginner", 4, "2-3"), ("Permutations & Combinations", "intermediate", 4, "2-3"),
    ("Simple Interest", "beginner", 4, "2"), ("Compound Interest", "beginner", 4, "2"),
    ("Partnership", "beginner", 3, "1-2"), ("Mixture & Alligation", "intermediate", 3, "1-2"),
    ("Boats & Streams", "beginner", 3, "1-2"), ("Trains Problems", "beginner", 3, "1-2"),
    ("Pipes & Cisterns", "beginner", 3, "1-2"), ("Calendar & Clocks", "intermediate", 3, "1-2"),
    ("Volume & Surface Area", "beginner", 3, "1-2"), ("Problems on Ages", "beginner", 3, "1-2"),
    ("Surds & Indices", "intermediate", 3, "1-2"), ("Square & Cube Roots", "beginner", 3, "1"),
    ("Simplification", "beginner", 3, "1-2"), ("Odd Man Out & Series", "intermediate", 3, "1-2"),
    ("Data Interpretation", "intermediate", 4, "2-3"), ("Successive Percentages", "intermediate", 4, "1-2"),
    ("Fraction to Percentage", "beginner", 4, "2"), ("Relative Speed", "intermediate", 4, "2"),
    ("Average Speed Problems", "intermediate", 4, "2"), ("Races & Games", "intermediate", 3, "1"),
    ("Linear Equations", "beginner", 3, "1-2"), ("Quadratic Equations", "intermediate", 3, "1"),
    ("Venn Diagrams", "beginner", 4, "2"), ("Percentage Change", "beginner", 4, "2"),
    ("Combined Work Problems", "intermediate", 4, "2"), ("Discount Problems", "intermediate", 4, "2"),
    ("False Weight Problems", "intermediate", 4, "2"), ("Population Growth", "intermediate", 3, "1"),
    ("Clock Angle Formula", "intermediate", 4, "2"), ("Calendar Day Finding", "intermediate", 3, "1"),
    ("Cylinder & Cone Problems", "beginner", 3, "1"), ("Sphere Problems", "beginner", 3, "1"),
    ("Number Series (Math)", "intermediate", 4, "2"), ("Coding-Decoding (Math)", "intermediate", 4, "2"),
    ("Blood Relations (Logic)", "intermediate", 4, "2"), ("Direction Sense", "beginner", 4, "2"),
    ("Sitting Arrangement", "intermediate", 4, "2"), ("Puzzles", "intermediate", 4, "2"),
    ("Data Sufficiency", "intermediate", 3, "1-2"), ("Syllogisms", "intermediate", 3, "1-2"),
    ("Statement & Conclusion", "intermediate", 3, "1-2"), ("Analogy (Verbal)", "intermediate", 3, "1-2"),
]
for t, d, i, e in quant_topics:
    add_bulk("Quantitative Aptitude", t, d, i, e)

print(f"After Quant: {len(cards)} cards")

# ===== ENGLISH (Cards 51-130) =====
english_topics = [
    ("Synonyms", "beginner", 5, "3-4"), ("Antonyms", "beginner", 5, "3-4"),
    ("Reading Comprehension", "intermediate", 5, "4-5"), ("Prepositions", "beginner", 4, "2-3"),
    ("Spotting Errors", "intermediate", 5, "3-4"), ("Sentence Completion", "intermediate", 4, "2-3"),
    ("Articles (a, an, the)", "beginner", 3, "1-2"), ("Idioms & Phrases", "intermediate", 4, "2-3"),
    ("Sentence Arrangement", "intermediate", 4, "2-3"), ("One Word Substitution", "beginner", 3, "1-2"),
    ("Para Jumbles", "intermediate", 4, "2"), ("Cloze Test", "intermediate", 3, "1-2"),
    ("Sentence Improvement", "intermediate", 3, "1-2"), ("Vocabulary Building", "beginner", 4, "2-3"),
    ("Analogies", "intermediate", 3, "1-2"), ("Subject-Verb Agreement", "beginner", 4, "2"),
    ("Tenses", "beginner", 4, "2"), ("Voice (Active/Passive)", "intermediate", 3, "1-2"),
    ("Narration (Direct/Indirect)", "intermediate", 3, "1-2"), ("Modifiers & Dangling Modifiers", "intermediate", 3, "1"),
    ("Parallelism", "intermediate", 3, "1"), ("Punctuation Rules", "beginner", 3, "1"),
    ("Conjunctions", "beginner", 3, "1"), ("Adjectives & Adverbs", "beginner", 3, "1"),
    ("Nouns & Pronouns", "beginner", 3, "1"), ("Gerunds & Participles", "intermediate", 2, "1"),
    ("Phrasal Verbs", "intermediate", 3, "1-2"), ("Collocations", "intermediate", 3, "1"),
    ("Homophones", "beginner", 3, "1"), ("Word Usage & Confusing Words", "beginner", 3, "1-2"),
    ("Critical Reasoning", "advanced", 3, "1"), ("Inference Questions", "intermediate", 3, "1"),
    ("Main Idea Questions", "intermediate", 3, "1"), ("Tone & Attitude Questions", "intermediate", 2, "1"),
    ("Fill in the Blanks", "beginner", 3, "1-2"), ("Double Blanks", "intermediate", 3, "1"),
    ("Vocabulary in Context", "intermediate", 3, "1"), ("Transition Words", "intermediate", 3, "1"),
    ("Sentence Simplification", "intermediate", 2, "1"), ("Critical Reading Strategies", "intermediate", 3, "1"),
]
for t, d, i, e in english_topics:
    add_bulk("English", t, d, i, e)

print(f"After English: {len(cards)} cards")

# ===== REASONING (Cards 131-200) =====
reasoning_topics = [
    ("Number Series", "intermediate", 5, "3-4"), ("Letter Series", "intermediate", 4, "2"),
    ("Coding-Decoding", "intermediate", 5, "3-4"), ("Blood Relations", "intermediate", 4, "2-3"),
    ("Direction Sense", "beginner", 4, "2-3"), ("Sitting Arrangement (Linear)", "intermediate", 5, "2-3"),
    ("Sitting Arrangement (Circular)", "advanced", 4, "2"), ("Puzzles", "intermediate", 5, "3-4"),
    ("Data Sufficiency", "intermediate", 4, "2"), ("Syllogisms", "intermediate", 4, "2"),
    ("Statement & Conclusion", "intermediate", 3, "1-2"), ("Statement & Assumption", "advanced", 3, "1"),
    ("Statement & Argument", "intermediate", 3, "1"), ("Course of Action", "intermediate", 3, "1"),
    ("Cause & Effect", "beginner", 3, "1"), ("Classification/Odd One Out", "beginner", 3, "1-2"),
    ("Analogy (Logical)", "intermediate", 4, "2"), ("Ranking & Order", "beginner", 3, "1-2"),
    ("Alphabet Test", "beginner", 3, "1"), ("Logical Venn Diagrams", "beginner", 3, "1"),
    ("Mathematical Operations", "intermediate", 3, "1"), ("Input-Output", "advanced", 4, "2"),
    ("Decision Making", "beginner", 3, "1"), ("Mirror & Water Images", "beginner", 3, "1"),
    ("Paper Folding & Cutting", "beginner", 3, "1"), ("Embedded Figures", "intermediate", 3, "1"),
    ("Figure Series", "intermediate", 3, "1"), ("Cube & Dice", "intermediate", 3, "1-2"),
    ("Dot Situation", "beginner", 2, "1"), ("Counting Figures", "beginner", 3, "1"),
    ("Analytical Reasoning", "advanced", 4, "2"), ("Logical Deduction", "advanced", 3, "1-2"),
    ("Truth & Lies Puzzles", "intermediate", 3, "1"), ("Matrix Matching", "intermediate", 3, "1"),
    ("Word Formation", "beginner", 3, "1"), ("Number Ranking", "beginner", 3, "1"),
    ("Missing Character", "intermediate", 3, "1"), ("Grouping of Figures", "intermediate", 2, "1"),
    ("Pattern Recognition", "intermediate", 4, "2"), ("Series Completion", "intermediate", 4, "2"),
]
for t, d, i, e in reasoning_topics:
    add_bulk("Reasoning", t, d, i, e)

print(f"After Reasoning: {len(cards)} cards")

# ===== COMPUTER FUNDAMENTALS (Cards 201-280) =====
cf_topics = [
    ("Number System & Conversions", "beginner", 5, "3-4"), ("CPU Architecture", "beginner", 5, "2-3"),
    ("Memory Types (RAM/ROM)", "beginner", 5, "2-3"), ("Cache Memory", "intermediate", 4, "2"),
    ("Secondary Storage Devices", "beginner", 4, "1-2"), ("I/O Devices", "beginner", 3, "1-2"),
    ("Data Representation", "intermediate", 4, "2"), ("Binary Arithmetic", "beginner", 4, "2"),
    ("Logic Gates", "beginner", 4, "2"), ("Boolean Algebra", "intermediate", 4, "2"),
    ("Flip-Flops", "intermediate", 3, "1"), ("Registers & Their Types", "beginner", 3, "1-2"),
    ("Instructions & Addressing Modes", "intermediate", 3, "1"), ("ALU & Control Unit", "beginner", 4, "2"),
    ("System Bus (Address/Data/Control)", "beginner", 3, "1"), ("Machine Cycle (Fetch-Decode-Execute)", "intermediate", 3, "1"),
    ("Interrupts", "intermediate", 3, "1"), ("DMA (Direct Memory Access)", "advanced", 2, "1"),
    ("Memory Hierarchy", "intermediate", 4, "2"), ("Virtual Memory Concept", "intermediate", 3, "1"),
    ("Algorithms & Flowcharts", "beginner", 5, "2-3"), ("Programming Paradigms", "beginner", 4, "2"),
    ("Data Types Basics", "beginner", 4, "1-2"), ("OOP Basics", "beginner", 4, "2"),
    ("Data Structures Basics", "beginner", 4, "1-2"), ("DBMS Basics", "beginner", 3, "1"),
    ("Network Basics", "beginner", 3, "1-2"), ("Internet & WWW", "beginner", 3, "1"),
    ("Security Basics (Virus, Malware)", "beginner", 3, "1"), ("Cloud Computing Introduction", "beginner", 3, "1"),
    ("Operating System Basics", "beginner", 4, "2"), ("Types of Operating Systems", "beginner", 3, "1"),
    ("High Level vs Low Level Languages", "beginner", 4, "2"), ("Compiler vs Interpreter", "beginner", 4, "2"),
    ("Assembler", "beginner", 3, "1"), ("Linker & Loader", "intermediate", 3, "1"),
    ("Programming Language Evaluation", "beginner", 3, "1"), ("Variable Declaration Basics", "beginner", 3, "1"),
    ("Conditional Statements Basics", "beginner", 3, "1"), ("Looping Constructs Basics", "beginner", 3, "1"),
    ("Functional Programming Intro", "intermediate", 3, "1"), ("Debugging & IDEs", "beginner", 3, "1"),
    ("History of Computers (Generations)", "beginner", 3, "1-2"),
]
for t, d, i, e in cf_topics:
    add_bulk("Computer Fundamentals", t, d, i, e)

print(f"After CF: {len(cards)} cards")

# ===== C PROGRAMMING (Cards 281-450) =====
c_topics = [
    ("History of C", "beginner", 3, "1"), ("C Standards (C89, C99, C11)", "beginner", 3, "1"),
    ("Keywords in C", "beginner", 4, "2"), ("Data Types in C", "beginner", 5, "3-4"),
    ("Type Modifiers (signed, unsigned, long, short)", "intermediate", 4, "2"),
    ("Type Qualifiers (const, volatile)", "intermediate", 3, "1-2"),
    ("Variables & Constants", "beginner", 4, "2"), ("Operators & Precedence", "intermediate", 5, "3-4"),
    ("Arithmetic Operators", "beginner", 4, "2"), ("Relational Operators", "beginner", 4, "2"),
    ("Logical Operators (&&, ||, !)", "beginner", 4, "2"), ("Bitwise Operators", "intermediate", 4, "2"),
    ("Assignment Operators", "beginner", 3, "1-2"), ("Conditional/Ternary Operator", "beginner", 3, "1"),
    ("Operator Associativity", "intermediate", 4, "2"), ("if-else Statement", "beginner", 4, "2"),
    ("switch-case Statement", "intermediate", 4, "2"), ("Nested if-else", "intermediate", 3, "1"),
    ("for Loop", "beginner", 5, "3-4"), ("while Loop", "beginner", 4, "2"),
    ("do-while Loop", "beginner", 4, "2"), ("Nested Loops", "intermediate", 4, "2"),
    ("break Statement", "beginner", 4, "2"), ("continue Statement", "beginner", 3, "1-2"),
    ("goto Statement", "beginner", 3, "1"), ("Functions Introduction", "beginner", 5, "3-4"),
    ("Function Declaration & Prototype", "beginner", 4, "2"), ("Function Definition", "beginner", 4, "2"),
    ("Function Call (Actual & Formal)", "beginner", 4, "2"), ("Parameter Passing", "intermediate", 4, "2"),
    ("Call by Value", "intermediate", 4, "2"), ("Call by Reference", "intermediate", 4, "2"),
    ("Recursion", "intermediate", 5, "3-4"), ("Storage Classes Overview", "intermediate", 4, "2"),
    ("auto Keyword", "beginner", 3, "1"), ("static Keyword", "intermediate", 4, "2"),
    ("extern Keyword", "intermediate", 3, "1"), ("register Keyword", "beginner", 3, "1"),
    ("1D Arrays", "beginner", 5, "3-4"), ("2D Arrays (Matrices)", "intermediate", 4, "2"),
    ("Array Traversal & Operations", "beginner", 4, "2"), ("Strings & String Handling", "beginner", 5, "3-4"),
    ("strlen() Function", "beginner", 4, "2"), ("strcpy() Function", "beginner", 4, "2"),
    ("strcmp() Function", "intermediate", 4, "2"), ("strcat() Function", "beginner", 4, "2"),
    ("strrev(), strlwr(), strupr()", "beginner", 3, "1"), ("Pointers Basics", "intermediate", 5, "3-4"),
    ("Pointer Declaration & Initialization", "intermediate", 5, "3"), ("Pointer Arithmetic", "advanced", 5, "3-4"),
    ("Pointer to Pointer", "advanced", 4, "2"), ("Array of Pointers", "advanced", 4, "2"),
    ("Pointer to Array", "advanced", 4, "2"), ("Function Pointer", "advanced", 3, "1"),
    ("Void Pointer (Generic Pointer)", "intermediate", 4, "2"), ("NULL Pointer", "intermediate", 4, "2"),
    ("Wild Pointer", "intermediate", 3, "1-2"), ("Dangling Pointer", "advanced", 3, "1-2"),
    ("Dynamic Memory Allocation Intro", "intermediate", 4, "2"), ("malloc() Function", "intermediate", 4, "2"),
    ("calloc() Function", "intermediate", 4, "2"), ("realloc() Function", "advanced", 3, "1"),
    ("free() Function", "intermediate", 4, "2"), ("Memory Leak in C", "intermediate", 3, "1"),
    ("Structures Basics", "intermediate", 5, "3"), ("Nested Structures", "advanced", 4, "2"),
    ("Array of Structures", "intermediate", 4, "2"), ("Pointer to Structure", "intermediate", 4, "2"),
    ("Structure Padding & Alignment", "advanced", 3, "1"), ("Unions", "intermediate", 4, "2"),
    ("Structure vs Union", "intermediate", 4, "2"), ("Bit Fields", "advanced", 3, "1"),
    ("typedef Keyword", "intermediate", 3, "1-2"), ("Enumerations (enum)", "intermediate", 3, "1-2"),
    ("Preprocessor Directives Overview", "intermediate", 4, "2"), ("#define & Macros", "intermediate", 4, "2"),
    ("Function-like Macros", "intermediate", 3, "1"), ("#include Directive", "beginner", 3, "1"),
    ("Conditional Compilation (#ifdef, #ifndef)", "advanced", 3, "1"),
    ("File Handling Introduction", "intermediate", 4, "2"), ("fopen() & fclose()", "intermediate", 4, "2"),
    ("fprintf() & fscanf()", "intermediate", 4, "2"), ("fgets() & fputs()", "intermediate", 3, "1"),
    ("fseek(), ftell(), rewind()", "advanced", 3, "1"), ("Sequential vs Random Access Files", "intermediate", 3, "1"),
    ("Command Line Arguments (argc, argv)", "intermediate", 3, "1"), ("Header Files Creation", "beginner", 3, "1"),
    ("Printf Format Specifiers", "beginner", 4, "2"), ("Scanf & Input Handling", "beginner", 4, "2"),
    ("Type Casting in C", "intermediate", 4, "2"), ("Scope of Variables", "beginner", 4, "2"),
    ("Lifetime of Variables", "intermediate", 3, "1"), ("Common C Programming Mistakes", "intermediate", 4, "2"),
]
for t, d, i, e in c_topics:
    add_bulk("C Programming", t, d, i, e)

print(f"After C Programming: {len(cards)} cards")

# ===== DATA STRUCTURES (Cards 451-570) =====
ds_topics = [
    ("Time Complexity Analysis", "intermediate", 5, "3-4"), ("Space Complexity", "intermediate", 4, "2"),
    ("Big-O Notation", "intermediate", 5, "3"), ("Big-Omega & Big-Theta", "advanced", 3, "1"),
    ("Best, Average, Worst Case", "intermediate", 4, "2"), ("Linear Search", "beginner", 4, "2"),
    ("Binary Search", "intermediate", 5, "3"), ("Binary Search Tree (BST)", "intermediate", 4, "2"),
    ("Stack Basics & LIFO", "beginner", 5, "3"), ("Stack Operations (push, pop, peek)", "beginner", 5, "3-4"),
    ("Infix Expression Notation", "intermediate", 4, "2"), ("Prefix (Polish) Notation", "intermediate", 4, "2"),
    ("Postfix (Reverse Polish) Notation", "intermediate", 4, "2"), ("Infix to Postfix Conversion", "intermediate", 4, "2"),
    ("Infix to Prefix Conversion", "advanced", 3, "1"), ("Postfix Expression Evaluation", "intermediate", 4, "2"),
    ("Balancing Parentheses", "intermediate", 4, "2"), ("Queue Basics & FIFO", "beginner", 5, "3"),
    ("Queue Operations (enqueue, dequeue)", "beginner", 5, "3"), ("Circular Queue", "intermediate", 4, "2"),
    ("Priority Queue", "intermediate", 3, "1-2"), ("Dequeue (Double-ended Queue)", "advanced", 3, "1"),
    ("Singly Linked List", "intermediate", 5, "3"), ("Doubly Linked List", "intermediate", 4, "2"),
    ("Circular Linked List", "intermediate", 4, "2"), ("Linked List Insertion", "intermediate", 4, "2"),
    ("Linked List Deletion", "intermediate", 4, "2"), ("Linked List Reversal", "intermediate", 4, "2"),
    ("Linked List Traversal", "beginner", 4, "2"), ("Trees Basics & Terminology", "beginner", 5, "3"),
    ("Binary Trees", "intermediate", 5, "3-4"), ("Tree Traversals Overview", "intermediate", 5, "3"),
    ("Inorder Traversal (LNR)", "intermediate", 5, "3"), ("Preorder Traversal (NLR)", "intermediate", 4, "2"),
    ("Postorder Traversal (LRN)", "intermediate", 4, "2"), ("Level Order Traversal (BFS)", "intermediate", 3, "1"),
    ("AVL Trees & Balancing", "advanced", 3, "1-2"), ("Tree Rotations (LL, RR, LR, RL)", "advanced", 3, "1"),
    ("B-Trees & B+ Trees", "advanced", 3, "1"), ("Spanning Trees & MST", "advanced", 3, "1"),
    ("Heap (Min-Heap & Max-Heap)", "intermediate", 3, "1-2"), ("Graphs Basics & Terminology", "intermediate", 4, "2"),
    ("Graph Representation (Adjacency Matrix/List)", "intermediate", 4, "2"),
    ("Breadth First Search (BFS)", "intermediate", 4, "2"), ("Depth First Search (DFS)", "intermediate", 4, "2"),
    ("Topological Sorting", "advanced", 3, "1"), ("Bubble Sort", "beginner", 4, "2"),
    ("Selection Sort", "beginner", 4, "2"), ("Insertion Sort", "beginner", 4, "2"),
    ("Merge Sort", "intermediate", 5, "3"), ("Quick Sort", "intermediate", 5, "3"),
    ("Heap Sort", "advanced", 3, "1"), ("Sorting Complexity Comparison", "intermediate", 5, "3"),
    ("Stable vs Unstable Sorting", "intermediate", 4, "2"), ("Divide & Conquer Paradigm", "intermediate", 4, "2"),
    ("Greedy Algorithms", "intermediate", 3, "1"), ("Hashing & Hash Functions", "intermediate", 4, "2"),
    ("Collision Handling (Chaining, Open Addressing)", "advanced", 3, "1"),
]
for t, d, i, e in ds_topics:
    add_bulk("Data Structures", t, d, i, e)

print(f"After Data Structures: {len(cards)} cards")

# ===== OOP C++ (Cards 571-680) =====
oop_topics = [
    ("Class & Object Basics", "beginner", 5, "3"), ("Access Specifiers (public, private, protected)", "beginner", 4, "2"),
    ("Constructors", "intermediate", 5, "3"), ("Default Constructor", "beginner", 4, "2"),
    ("Parameterized Constructor", "intermediate", 4, "2"), ("Copy Constructor", "intermediate", 4, "2"),
    ("Destructor", "intermediate", 5, "3"), ("Function Overloading", "intermediate", 4, "2"),
    ("Operator Overloading", "advanced", 3, "1-2"), ("Friend Function", "advanced", 3, "1"),
    ("Friend Class", "advanced", 2, "1"), ("this Pointer", "intermediate", 4, "2"),
    ("Static Data Members", "intermediate", 4, "2"), ("Static Member Functions", "intermediate", 3, "1-2"),
    ("References in C++", "intermediate", 4, "2"), ("Inline Functions", "intermediate", 3, "1-2"),
    ("Default Arguments", "beginner", 3, "1"), ("Inheritance Basics", "intermediate", 5, "3"),
    ("Single Inheritance", "intermediate", 5, "3"), ("Multiple Inheritance", "advanced", 4, "2"),
    ("Multilevel Inheritance", "intermediate", 4, "2"), ("Hierarchical Inheritance", "intermediate", 3, "1-2"),
    ("Hybrid Inheritance", "advanced", 3, "1"), ("Virtual Inheritance (Diamond Problem)", "advanced", 3, "1"),
    ("Virtual Functions", "advanced", 5, "3"), ("Pure Virtual Functions", "advanced", 4, "2"),
    ("Abstract Classes", "advanced", 4, "2"), ("Interfaces in C++", "advanced", 3, "1"),
    ("Function Overriding", "intermediate", 4, "2"), ("Early Binding (Compile-time)", "intermediate", 3, "1"),
    ("Late Binding (Runtime Polymorphism)", "advanced", 4, "2"),
    ("Templates (Function & Class)", "advanced", 3, "1"), ("Exception Handling Basics", "intermediate", 4, "2"),
    ("try-catch Block", "intermediate", 4, "2"), ("throw Keyword", "intermediate", 3, "1-2"),
    ("Multiple Catch Blocks", "intermediate", 3, "1"), ("RTTI (Runtime Type Info)", "advanced", 3, "1"),
    ("typeid Operator", "advanced", 2, "1"), ("Casting Operators in C++", "advanced", 2, "1"),
    ("C++ vs C Key Differences", "beginner", 4, "2"), ("Encapsulation", "beginner", 5, "3"),
    ("Data Abstraction", "intermediate", 4, "2"), ("Polymorphism (Types)", "intermediate", 5, "3"),
    ("Compile-time Polymorphism", "intermediate", 4, "2"), ("Runtime Polymorphism", "advanced", 4, "2"),
    ("Object Slicing", "advanced", 3, "1"), ("Virtual Destructor", "advanced", 4, "2"),
    ("Namespace in C++", "intermediate", 3, "1"), ("new vs malloc in C++", "intermediate", 4, "2"),
    ("delete vs free in C++", "intermediate", 3, "1"),
]
for t, d, i, e in oop_topics:
    add_bulk("OOP C++", t, d, i, e)

print(f"After OOP: {len(cards)} cards")

# ===== OPERATING SYSTEMS (Cards 681-780) =====
os_topics = [
    ("Process vs Program", "beginner", 5, "3"), ("Process States (New, Ready, Running, Wait, Terminate)", "intermediate", 5, "3"),
    ("Process Control Block (PCB)", "intermediate", 4, "2"), ("Process Scheduling Overview", "intermediate", 5, "3"),
    ("FCFS Scheduling Algorithm", "intermediate", 5, "3"), ("SJF Scheduling Algorithm", "intermediate", 5, "3"),
    ("SRTF (Preemptive SJF)", "intermediate", 4, "2"), ("Priority Scheduling", "intermediate", 4, "2"),
    ("Round Robin Scheduling", "intermediate", 5, "3"), ("Multilevel Queue Scheduling", "advanced", 3, "1"),
    ("CPU Scheduling Criteria", "intermediate", 3, "1-2"), ("Gantt Charts", "intermediate", 4, "2"),
    ("Context Switching", "intermediate", 4, "2"), ("Deadlock Introduction", "intermediate", 5, "3"),
    ("4 Conditions of Deadlock", "intermediate", 5, "3"), ("Deadlock Prevention", "intermediate", 4, "2"),
    ("Deadlock Avoidance (Banker's Algorithm)", "advanced", 3, "1-2"),
    ("Deadlock Detection & Recovery", "advanced", 3, "1"), ("Memory Management Overview", "beginner", 5, "3"),
    ("Paging", "intermediate", 5, "3"), ("Segmentation", "intermediate", 4, "2"),
    ("Page Table & TLB", "intermediate", 4, "2"), ("Page Fault Handling", "intermediate", 4, "2"),
    ("Virtual Memory", "intermediate", 5, "3"), ("Demand Paging", "intermediate", 5, "3"),
    ("Page Replacement (FIFO)", "intermediate", 4, "2"), ("Page Replacement (LRU)", "intermediate", 4, "2"),
    ("Page Replacement (Optimal)", "advanced", 3, "1"), ("Thrashing", "intermediate", 4, "2"),
    ("Belady's Anomaly", "advanced", 3, "1"), ("File System Structure", "beginner", 3, "1-2"),
    ("File Allocation Methods", "intermediate", 3, "1"), ("Disk Scheduling (FCFS, SCAN, C-SCAN)", "intermediate", 4, "2"),
    ("Process Synchronization", "intermediate", 4, "2"), ("Critical Section Problem", "intermediate", 4, "2"),
    ("Semaphores (Binary & Counting)", "intermediate", 4, "2"), ("Mutex vs Semaphore", "intermediate", 4, "2"),
    ("Producer-Consumer Problem", "intermediate", 4, "2"), ("Dining Philosophers Problem", "advanced", 3, "1"),
    ("Readers-Writers Problem", "advanced", 3, "1"), ("IPC Mechanisms", "intermediate", 3, "1"),
    ("System Calls", "beginner", 3, "1-2"), ("Kernel Mode vs User Mode", "beginner", 4, "2"),
    ("Thread vs Process", "intermediate", 4, "2"), ("Memory Fragmentation (Internal/External)", "intermediate", 4, "2"),
    ("Swapping", "intermediate", 3, "1"), ("Scheduling Parameters (Throughput, Turnaround)", "intermediate", 3, "1"),
]
for t, d, i, e in os_topics:
    add_bulk("Operating Systems", t, d, i, e)

print(f"After OS: {len(cards)} cards")

# ===== NETWORKING (Cards 781-880) =====
nw_topics = [
    ("OSI Model - 7 Layers", "intermediate", 5, "3-4"), ("Physical Layer", "beginner", 4, "2"),
    ("Data Link Layer", "intermediate", 4, "2"), ("Network Layer", "intermediate", 5, "3"),
    ("Transport Layer", "intermediate", 5, "3"), ("Session Layer", "beginner", 3, "1"),
    ("Presentation Layer", "beginner", 3, "1"), ("Application Layer", "beginner", 4, "2"),
    ("TCP/IP Model (4 Layers)", "intermediate", 5, "3-4"), ("OSI vs TCP/IP Comparison", "intermediate", 4, "2"),
    ("TCP Protocol", "intermediate", 5, "3-4"), ("UDP Protocol", "intermediate", 5, "3"),
    ("TCP vs UDP Comparison", "intermediate", 5, "3-4"), ("TCP 3-Way Handshake", "intermediate", 4, "2"),
    ("IP Addressing (IPv4)", "intermediate", 5, "3"), ("IPv4 vs IPv6", "intermediate", 4, "2"),
    ("IP Address Classes (A, B, C, D, E)", "intermediate", 5, "3"), ("Subnetting", "advanced", 4, "2"),
    ("Subnet Mask", "advanced", 4, "2"), ("CIDR Notation", "advanced", 3, "1"),
    ("ARP Protocol", "intermediate", 4, "2"), ("RARP Protocol", "advanced", 3, "1"),
    ("ICMP Protocol", "intermediate", 4, "2"), ("DNS System", "intermediate", 5, "3"),
    ("DNS Resolution Process", "intermediate", 4, "2"), ("HTTP Protocol", "intermediate", 5, "3"),
    ("HTTPS vs HTTP", "intermediate", 4, "2"), ("FTP Protocol", "intermediate", 4, "2"),
    ("SMTP, POP3, IMAP", "beginner", 3, "1"), ("Telnet & SSH", "beginner", 3, "1"),
    ("Ports and Sockets", "intermediate", 4, "2"), ("Well-Known Ports", "intermediate", 4, "2"),
    ("Routing Basics", "intermediate", 4, "2"), ("Routing Protocols (RIP, OSPF, BGP)", "advanced", 3, "1"),
    ("Network Devices (Hub, Switch, Router)", "beginner", 4, "2"), ("Gateway", "intermediate", 3, "1"),
    ("Firewall", "beginner", 4, "2"), ("Network Topologies", "beginner", 3, "1-2"),
    ("Client-Server Model", "beginner", 4, "2"), ("Peer-to-Peer Model", "beginner", 3, "1"),
    ("Cloud Computing Basics", "beginner", 3, "1"), ("Virtualization", "intermediate", 3, "1"),
    ("Transmission Media (Guided/Unguided)", "beginner", 3, "1"), ("Error Detection (CRC, Checksum)", "intermediate", 3, "1"),
    ("HTTP Status Codes", "beginner", 3, "1"), ("GET vs POST", "beginner", 3, "1"),
    ("Cookies & Sessions", "beginner", 3, "1"), ("NAT (Network Address Translation)", "intermediate", 3, "1"),
]
for t, d, i, e in nw_topics:
    add_bulk("Networking", t, d, i, e)

print(f"After Networking: {len(cards)} cards")

# ===== DBMS (Cards 881-970) =====
dbms_topics = [
    ("DBMS vs File System", "beginner", 5, "3"), ("DBMS Architecture (3-Schema)", "beginner", 4, "2"),
    ("Data Models (Hierarchical, Network, Relational)", "intermediate", 4, "2"),
    ("Relational Model Concepts", "intermediate", 5, "3"), ("Keys in DBMS Overview", "intermediate", 5, "3-4"),
    ("Primary Key", "beginner", 5, "3"), ("Foreign Key", "intermediate", 5, "3"),
    ("Candidate Key", "intermediate", 4, "2"), ("Super Key", "intermediate", 4, "2"),
    ("ER Model & ER Diagrams", "intermediate", 5, "3"), ("Entity & Attributes", "beginner", 4, "2"),
    ("Relationships & Cardinality", "intermediate", 4, "2"), ("Normalization Overview", "intermediate", 5, "3-4"),
    ("1NF (First Normal Form)", "intermediate", 5, "3"), ("2NF (Second Normal Form)", "intermediate", 5, "3"),
    ("3NF (Third Normal Form)", "intermediate", 5, "3"), ("BCNF (Boyce-Codd)", "advanced", 4, "2"),
    ("Functional Dependencies", "intermediate", 4, "2"), ("SQL Basics & DDL Commands", "beginner", 5, "3"),
    ("DML Commands (INSERT, UPDATE, DELETE)", "beginner", 4, "2"), ("SELECT Statement", "beginner", 5, "3"),
    ("WHERE Clause & Operators", "beginner", 4, "2"), ("ORDER BY & GROUP BY", "intermediate", 4, "2"),
    ("JOINs (Inner, Left, Right, Full)", "intermediate", 5, "3"), ("Subqueries", "intermediate", 4, "2"),
    ("Aggregate Functions (COUNT, SUM, AVG, MAX, MIN)", "intermediate", 4, "2"),
    ("Views", "intermediate", 3, "1"), ("Indexes", "intermediate", 4, "2"),
    ("Transactions & ACID Properties", "intermediate", 5, "3"), ("Concurrency Control", "advanced", 3, "1"),
    ("Locking Protocols & 2-Phase Locking", "advanced", 3, "1"), ("Deadlock in DBMS", "advanced", 3, "1"),
    ("NoSQL Databases", "beginner", 3, "1"), ("SQL vs NoSQL", "beginner", 3, "1-2"),
    ("Anomalies (Insert, Update, Delete)", "intermediate", 4, "2"), ("Denormalization", "advanced", 2, "1"),
    ("Stored Procedures & Triggers", "intermediate", 3, "1"), ("Database Security", "beginner", 3, "1"),
]
for t, d, i, e in dbms_topics:
    add_bulk("DBMS", t, d, i, e)

print(f"After DBMS: {len(cards)} cards")

# ===== BIG DATA & AI (Cards 971-1050) =====
ai_topics = [
    ("Big Data 5Vs (Volume, Velocity, Variety, Veracity, Value)", "beginner", 4, "2"),
    ("Structured Data", "beginner", 4, "2"), ("Semi-Structured Data", "beginner", 3, "1"),
    ("Unstructured Data", "beginner", 4, "2"), ("NoSQL Databases", "beginner", 3, "1"),
    ("BASE Properties", "beginner", 3, "1"), ("CAP Theorem", "intermediate", 4, "2"),
    ("Data Warehouse", "intermediate", 3, "1"), ("OLAP vs OLTP", "intermediate", 4, "2"),
    ("Hadoop Ecosystem", "intermediate", 4, "2"), ("HDFS (Hadoop Distributed FS)", "intermediate", 4, "2"),
    ("MapReduce", "intermediate", 4, "2"), ("Apache Hive", "beginner", 3, "1"),
    ("Apache Spark", "beginner", 3, "1"), ("Batch Processing", "intermediate", 3, "1"),
    ("Stream Processing", "intermediate", 3, "1"), ("ETL vs ELT", "intermediate", 3, "1"),
    ("Data Cleansing", "beginner", 3, "1"), ("Data Modeling", "intermediate", 3, "1"),
    ("Introduction to AI", "beginner", 4, "2"), ("Intelligent Agents", "beginner", 3, "1"),
    ("Turing Test", "beginner", 3, "1"), ("Machine Learning Basics", "beginner", 4, "2"),
    ("Supervised Learning", "intermediate", 4, "2"), ("Unsupervised Learning", "intermediate", 4, "2"),
    ("Reinforcement Learning", "intermediate", 3, "1"), ("Linear Regression", "intermediate", 3, "1"),
    ("Logistic Regression", "intermediate", 3, "1"), ("Decision Trees", "intermediate", 3, "1"),
    ("K-Means Clustering", "intermediate", 3, "1"), ("KNN Algorithm", "intermediate", 3, "1"),
    ("Neural Networks Basics", "intermediate", 4, "2"), ("Perceptron", "intermediate", 3, "1"),
    ("Deep Learning", "intermediate", 3, "1"), ("CNN (Convolutional Neural Network)", "advanced", 3, "1"),
    ("RNN (Recurrent Neural Network)", "advanced", 2, "1"), ("Backpropagation", "advanced", 3, "1"),
    ("Activation Functions", "intermediate", 3, "1"), ("Gradient Descent", "advanced", 3, "1"),
    ("Overfitting & Underfitting", "intermediate", 3, "1"), ("Natural Language Processing", "beginner", 3, "1"),
    ("Computer Vision", "beginner", 3, "1"), ("Data Science Pipeline", "beginner", 3, "1"),
    ("Feature Engineering", "intermediate", 3, "1"), ("Model Evaluation Metrics", "intermediate", 3, "1"),
    ("Precision, Recall, F1-Score", "intermediate", 3, "1"), ("Confusion Matrix", "intermediate", 3, "1"),
    ("Python for Data Science", "beginner", 3, "1"),
]
for t, d, i, e in ai_topics:
    add_bulk("Big Data & AI", t, d, i, e)

print(f"After AI: {len(cards)} cards")

# ===== ADDITIONAL HIGH-YIELD DEEP DIVES (Cards 1051-1150) =====
extra = [
    ("Quantitative Aptitude", "Percentage to Fraction Conversion Table", "beginner", 5, "2"),
    ("Quantitative Aptitude", "Marked Price vs Selling Price vs Cost Price", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Successive Discounts Formula", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Compound Interest with Installments", "advanced", 3, "1"),
    ("Quantitative Aptitude", "Depreciation Formula", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Alligation Rule & Diagram", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Clock Hands Coincidence Problems", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Leap Year Rules & Calendar Shortcuts", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Train Crossing Man/Platform/Bridge", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Two Trains Moving in Same/Opposite Direction", "intermediate", 3, "1"),
    ("C Programming", "Printf Format Specifiers (%d, %f, %s, %c)", "beginner", 4, "2"),
    ("C Programming", "Type Casting (Implicit vs Explicit)", "intermediate", 4, "2"),
    ("C Programming", "Scope Rules (Block, Function, File)", "beginner", 4, "2"),
    ("C Programming", "Common C Errors (Segmentation Fault, etc.)", "intermediate", 4, "2"),
    ("C Programming", "Multiple File Programs & Header Guards", "intermediate", 3, "1"),
    ("Data Structures", "Choosing Right Data Structure", "intermediate", 4, "2"),
    ("Data Structures", "In-place vs Extra-space Sorting", "intermediate", 3, "1"),
    ("Data Structures", "Comparison-based Sorting Lower Bound", "advanced", 3, "1"),
    ("Data Structures", "Stack Applications (Undo, Recursion, etc.)", "intermediate", 4, "2"),
    ("Data Structures", "Queue Applications (BFS, Scheduling)", "intermediate", 4, "2"),
    ("Operating Systems", "Types of OS (Batch, Time-Share, Real-Time)", "beginner", 3, "1"),
    ("Operating Systems", "Multithreading Models", "advanced", 3, "1"),
    ("Operating Systems", "Internal vs External Fragmentation", "intermediate", 3, "1"),
    ("Operating Systems", "Compaction & Paging Trade-offs", "advanced", 2, "1"),
    ("Operating Systems", "Throughput, Turnaround, Waiting, Response Time", "intermediate", 3, "1"),
    ("Networking", "Guided Media (Twisted Pair, Coaxial, Fiber)", "beginner", 3, "1"),
    ("Networking", "Unguided Media (Radio, Microwave, Satellite)", "beginner", 3, "1"),
    ("Networking", "Error Detection Methods (CRC, Checksum)", "intermediate", 3, "1"),
    ("Networking", "Flow Control & Congestion Control", "advanced", 2, "1"),
    ("Networking", "HTTP Methods (GET, POST, PUT, DELETE)", "beginner", 3, "1"),
    ("DBMS", "Anomalies: Insert, Update, Delete", "intermediate", 4, "2"),
    ("DBMS", "Dependency Preservation & Lossless Join", "advanced", 2, "1"),
    ("DBMS", "Data Dictionary & Metadata", "beginner", 3, "1"),
    ("DBMS", "Cursors in SQL", "advanced", 2, "1"),
    ("DBMS", "Backup & Recovery Techniques", "beginner", 3, "1"),
    ("DBMS", "Data Mining Basics", "beginner", 3, "1"),
    ("OOP C++", "Object Slicing Problem", "advanced", 3, "1"),
    ("OOP C++", "Virtual Destructor Need", "advanced", 4, "2"),
    ("OOP C++", "Namespace & using Directive", "intermediate", 3, "1"),
    ("OOP C++", "Dynamic Cast & Static Cast", "advanced", 2, "1"),
    ("OOP C++", "Exception Safety & RAII", "advanced", 2, "1"),
]
for subj, t, d, i, e in extra:
    add_bulk(subj, t, d, i, e)

print(f"After Extra batch 1: {len(cards)} cards")

# ===== SECOND BATCH: More deep-dive topics (to reach 1000+) =====
extra2 = [
    # More Quant subtopics
    ("Quantitative Aptitude", "Percentage Increase & Decrease", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Converting Percentage to Decimal", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Finding Original from Percentage", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Revenue & Tax Problems", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Commission & Brokerage", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Simple Interest vs Compound Interest", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Half-Yearly & Quarterly CI", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Difference between SI and CI", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Ratio of Three or More Quantities", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Direct & Inverse Proportion", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Weighted Average Problems", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Average of Consecutive Numbers", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Pipes Filling & Emptying Tank", "beginner", 3, "1-2"),
    ("Quantitative Aptitude", "Efficiency Based Work Problems", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Wages Based on Work Done", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Speed Conversion (km/h to m/s)", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Problems on Upstream/Downstream", "beginner", 3, "1-2"),
    ("Quantitative Aptitude", "Race Problems (A beats B by x meters)", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Conditional Probability", "advanced", 3, "1"),
    ("Quantitative Aptitude", "Bayes Theorem Basics", "advanced", 2, "1"),
    ("Quantitative Aptitude", "Properties of HCF", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Properties of LCM", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Finding Unit Digit of Large Powers", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Finding Number of Zeros", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Divisibility by 7, 11, 13", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Sum of Natural Numbers Formula", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Sum of Squares & Cubes", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Arrangement in Groups", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Circular Permutation Problems", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Handshakes & Polygon Diagonals", "beginner", 3, "1"),
    # More English
    ("English", "Comparative & Superlative Forms", "beginner", 3, "1"),
    ("English", "Irregular Verbs", "beginner", 3, "1"),
    ("English", "Modal Verbs (can, could, may, might)", "beginner", 3, "1"),
    ("English", "Infinitives & Gerunds Usage", "intermediate", 3, "1"),
    ("English", "Participles (Present & Past)", "intermediate", 3, "1"),
    ("English", "Relative Clauses (who, which, that)", "intermediate", 3, "1"),
    ("English", "Conditional Sentences (If clauses)", "intermediate", 3, "1"),
    ("English", "Reported Speech Rules", "intermediate", 3, "1"),
    ("English", "Commonly Confused Words", "beginner", 4, "2"),
    ("English", "Prefix & Suffix Word Building", "beginner", 3, "1"),
    ("English", "Context Clues for Vocabulary", "intermediate", 3, "1"),
    ("English", "Fact vs Inference in RC", "intermediate", 3, "1"),
    ("English", "Author's Purpose & Tone", "intermediate", 3, "1"),
    ("English", "Elimination Strategy for MCQs", "beginner", 4, "2"),
    ("English", "Time Management in English Section", "beginner", 3, "1"),
    # More Reasoning
    ("Reasoning", "Letter Analogy", "intermediate", 3, "1"),
    ("Reasoning", "Number Analogy", "intermediate", 3, "1"),
    ("Reasoning", "Verbal Classification", "beginner", 3, "1"),
    ("Reasoning", "Essential Part Selection", "intermediate", 3, "1"),
    ("Reasoning", "Artificial Language Problems", "intermediate", 3, "1"),
    ("Reasoning", "Matching Definitions", "beginner", 3, "1"),
    ("Reasoning", "Verbal Reasoning (True/False/Cannot Say)", "intermediate", 3, "1"),
    ("Reasoning", "Making Judgments from Statements", "intermediate", 3, "1"),
    ("Reasoning", "Logical Games & Puzzles", "advanced", 4, "2"),
    ("Reasoning", "Scheduling Puzzles", "advanced", 3, "1"),
    ("Reasoning", "Comparison Puzzles", "intermediate", 3, "1"),
    ("Reasoning", "Selection Puzzles", "intermediate", 3, "1"),
    ("Reasoning", "Seating Arrangement with Conditions", "advanced", 4, "2"),
    ("Reasoning", "Floor Based Puzzles", "advanced", 3, "1"),
    ("Reasoning", "Box Based Puzzles", "intermediate", 3, "1"),
    # More C Programming
    ("C Programming", "Bitwise Operations in Practice", "intermediate", 4, "2"),
    ("C Programming", "Left Shift & Right Shift Operators", "intermediate", 4, "2"),
    ("C Programming", "Masking & Bit Manipulation", "advanced", 3, "1"),
    ("C Programming", "Endianness (Big vs Little)", "advanced", 3, "1"),
    ("C Programming", "Stack vs Heap Memory", "intermediate", 4, "2"),
    ("C Programming", "Memory Layout of C Program", "intermediate", 4, "2"),
    ("C Programming", "Recursion vs Iteration", "intermediate", 4, "2"),
    ("C Programming", "Tower of Hanoi Problem", "advanced", 3, "1"),
    ("C Programming", "Fibonacci with Recursion", "intermediate", 4, "2"),
    ("C Programming", "Factorial Using Recursion", "beginner", 4, "2"),
    ("C Programming", "GCD Using Recursion", "intermediate", 3, "1"),
    ("C Programming", "Static vs Dynamic Libraries", "advanced", 2, "1"),
    ("C Programming", "Makefile Basics", "beginner", 2, "1"),
    ("C Programming", "Common C Interview Questions", "intermediate", 4, "2"),
    ("C Programming", "C Programming Best Practices", "beginner", 3, "1"),
    # More Data Structures
    ("Data Structures", "Doubly Linked List Operations", "intermediate", 4, "2"),
    ("Data Structures", "Circular Linked List Operations", "intermediate", 3, "1"),
    ("Data Structures", "Skip List Concept", "advanced", 2, "1"),
    ("Data Structures", "Self-Balancing Trees Overview", "advanced", 3, "1"),
    ("Data Structures", "Red-Black Trees Concept", "advanced", 2, "1"),
    ("Data Structures", "Trie (Prefix Tree)", "advanced", 3, "1"),
    ("Data Structures", "Segment Tree Concept", "advanced", 2, "1"),
    ("Data Structures", "Graph Cycle Detection", "advanced", 3, "1"),
    ("Data Structures", "Graph Connectivity", "intermediate", 3, "1"),
    ("Data Structures", "Weighted Graph Problems", "advanced", 3, "1"),
    ("Data Structures", "Kruskal's Algorithm", "advanced", 3, "1"),
    ("Data Structures", "Prim's Algorithm", "advanced", 2, "1"),
    ("Data Structures", "Bellman-Ford Algorithm", "advanced", 2, "1"),
    ("Data Structures", "Floyd-Warshall Algorithm", "advanced", 2, "1"),
    ("Data Structures", "Counting Sort & Radix Sort", "advanced", 2, "1"),
    # More OOP
    ("OOP C++", "Multiple Inheritance Ambiguity", "advanced", 3, "1"),
    ("OOP C++", "Virtual Base Class", "advanced", 3, "1"),
    ("OOP C++", "Vtable & Vptr Internals", "advanced", 3, "1"),
    ("OOP C++", "Pure Virtual Destructor", "advanced", 2, "1"),
    ("OOP C++", "Abstract Class vs Interface", "advanced", 3, "1"),
    ("OOP C++", "Covariant Return Types", "advanced", 2, "1"),
    ("OOP C++", "Operator Overloading Rules", "advanced", 3, "1"),
    ("OOP C++", "Overloading ++ and -- (Prefix/Postfix)", "advanced", 3, "1"),
    ("OOP C++", "Overloading [] and ()", "advanced", 2, "1"),
    ("OOP C++", "Type Conversion in C++", "advanced", 3, "1"),
    ("OOP C++", "C++11/14/17 Features Overview", "intermediate", 3, "1"),
    ("OOP C++", "Smart Pointers (unique, shared, weak)", "advanced", 3, "1"),
    ("OOP C++", "Lambda Expressions in C++", "advanced", 2, "1"),
    ("OOP C++", "STL Containers Overview", "intermediate", 3, "1"),
    ("OOP C++", "STL Algorithms Overview", "intermediate", 2, "1"),
    # More OS
    ("Operating Systems", "Process Creation (fork, exec)", "intermediate", 3, "1"),
    ("Operating Systems", "Process Termination Conditions", "intermediate", 3, "1"),
    ("Operating Systems", "User Thread vs Kernel Thread", "advanced", 3, "1"),
    ("Operating Systems", "Many-to-One Threading Model", "advanced", 2, "1"),
    ("Operating Systems", "One-to-One Threading Model", "advanced", 2, "1"),
    ("Operating Systems", "Many-to-Many Threading Model", "advanced", 2, "1"),
    ("Operating Systems", "Scheduling: Preemptive vs Non-preemptive", "intermediate", 4, "2"),
    ("Operating Systems", "Starvation in Scheduling", "intermediate", 3, "1"),
    ("Operating Systems", "Aging Technique", "advanced", 2, "1"),
    ("Operating Systems", "Frame Allocation (Equal/Proportional)", "advanced", 2, "1"),
    ("Operating Systems", "Copy-on-Write (COW)", "advanced", 3, "1"),
    ("Operating Systems", "File Access Methods (Sequential/Direct)", "intermediate", 3, "1"),
    ("Operating Systems", "Directory Structure (Single/Two-level/Tree)", "intermediate", 3, "1"),
    ("Operating Systems", "Disk Free Space Management", "advanced", 2, "1"),
    ("Operating Systems", "RAID Levels (0,1,5,6)", "intermediate", 3, "1"),
    # More Networking
    ("Networking", "Unicast, Multicast, Broadcast", "beginner", 3, "1"),
    ("Networking", "Symmetric vs Asymmetric Encryption", "beginner", 3, "1"),
    ("Networking", "Digital Signatures", "beginner", 3, "1"),
    ("Networking", "SSL/TLS Handshake", "intermediate", 3, "1"),
    ("Networking", "TCP Congestion Control", "advanced", 3, "1"),
    ("Networking", "TCP Flow Control (Sliding Window)", "advanced", 3, "1"),
    ("Networking", "UDP Use Cases (DNS, Gaming, Streaming)", "beginner", 3, "1"),
    ("Networking", "IPv4 Header Format", "advanced", 2, "1"),
    ("Networking", "IPv6 Header Format", "advanced", 2, "1"),
    ("Networking", "ICMP Message Types", "intermediate", 3, "1"),
    ("Networking", "DHCP Process (DORA)", "intermediate", 3, "1"),
    ("Networking", "ARP Spoofing & Security", "intermediate", 3, "1"),
    ("Networking", "DNS Record Types (A, AAAA, MX, CNAME)", "intermediate", 3, "1"),
    ("Networking", "Proxy vs Reverse Proxy", "beginner", 3, "1"),
    ("Networking", "Load Balancing Basics", "beginner", 3, "1"),
    # More DBMS
    ("DBMS", "CHECK, UNIQUE, NOT NULL Constraints", "beginner", 4, "2"),
    ("DBMS", "Referential Integrity", "intermediate", 4, "2"),
    ("DBMS", "UNION, INTERSECT, EXCEPT", "intermediate", 3, "1"),
    ("DBMS", "HAVING vs WHERE", "intermediate", 4, "2"),
    ("DBMS", "EXISTS vs IN in Subqueries", "intermediate", 3, "1"),
    ("DBMS", "Correlated Subqueries", "advanced", 3, "1"),
    ("DBMS", "Window Functions (ROW_NUMBER, RANK)", "advanced", 3, "1"),
    ("DBMS", "Temporary Tables", "intermediate", 2, "1"),
    ("DBMS", "Materialized Views", "advanced", 2, "1"),
    ("DBMS", "Query Optimization Basics", "intermediate", 3, "1"),
    ("DBMS", "Index Types (B-Tree, Hash, Bitmap)", "intermediate", 3, "1"),
    ("DBMS", "Database Sharding", "advanced", 2, "1"),
    ("DBMS", "CAP Theorem in NoSQL", "intermediate", 3, "1"),
    ("DBMS", "MongoDB vs MySQL Comparison", "beginner", 3, "1"),
    ("DBMS", "Data Warehousing Concepts", "beginner", 3, "1"),
    # More Big Data & AI
    ("Big Data & AI", "Random Forest Algorithm", "advanced", 2, "1"),
    ("Big Data & AI", "Naive Bayes Classifier", "intermediate", 3, "1"),
    ("Big Data & AI", "Dimensionality Reduction (PCA)", "advanced", 2, "1"),
    ("Big Data & AI", "Transfer Learning", "advanced", 2, "1"),
    ("Big Data & AI", "Generative Adversarial Networks", "advanced", 2, "1"),
    ("Big Data & AI", "Word Embeddings (Word2Vec)", "advanced", 2, "1"),
    ("Big Data & AI", "Attention Mechanism", "advanced", 2, "1"),
    ("Big Data & AI", "Transformer Architecture", "advanced", 2, "1"),
    ("Big Data & AI", "BERT & GPT Overview", "advanced", 2, "1"),
    ("Big Data & AI", "Reinforcement Learning (Q-Learning)", "advanced", 2, "1"),
    ("Big Data & AI", "A* Search Algorithm", "advanced", 2, "1"),
    ("Big Data & AI", "IoT (Internet of Things)", "beginner", 3, "1"),
    ("Big Data & AI", "Edge Computing", "beginner", 2, "1"),
    ("Big Data & AI", "Blockchain Basics", "beginner", 3, "1"),
    ("Big Data & AI", "Cybersecurity Fundamentals", "beginner", 3, "1"),
]
for subj, t, d, i, e in extra2:
    add_bulk(subj, t, d, i, e)

print(f"After Extra batch 2: {len(cards)} cards")

# ===== THIRD BATCH: Final cards to reach 1000+ =====
extra3 = [
    # More detailed subtopics for high-yield areas
    ("Quantitative Aptitude", "Percentage Error in Measurement", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Cost Price from Selling Price & Profit%", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Selling Price from Cost Price & Loss%", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Partnership: Sleeping vs Working Partner", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Mixture: Replacing Part of Solution", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Boats: Speed of Stream Calculation", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Compound Interest: Rate Computation", "advanced", 2, "1"),
    ("Quantitative Aptitude", "Present Value & Future Value", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Work: Negative Work (Leakage)", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Cistern: Time to Fill/Empty", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Tournament (Knockout Matches)", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Games: Points Table Problems", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Probability: Drawing with Replacement", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Probability: Drawing without Replacement", "intermediate", 4, "2"),
    ("Quantitative Aptitude", "Numbers: Finding Sum of Factors", "intermediate", 3, "1"),
    ("C Programming", "EOF and File End Detection", "beginner", 3, "1"),
    ("C Programming", "getchar() and putchar() Functions", "beginner", 3, "1"),
    ("C Programming", "sprintf() and sscanf() Usage", "intermediate", 3, "1"),
    ("C Programming", "Variable Length Arguments (stdarg.h)", "advanced", 2, "1"),
    ("C Programming", "Signal Handling in C", "advanced", 2, "1"),
    ("C Programming", "setjmp and longjmp", "advanced", 2, "1"),
    ("C Programming", "Flexible Array Members", "advanced", 2, "1"),
    ("C Programming", "Inline Assembly in C", "advanced", 2, "1"),
    ("C Programming", "C Interview: Find Missing Number", "intermediate", 4, "2"),
    ("C Programming", "C Interview: Swap Without Temp", "beginner", 4, "2"),
    ("C Programming", "C Interview: Reverse a String", "beginner", 4, "2"),
    ("C Programming", "C Interview: Check Palindrome", "beginner", 4, "2"),
    ("C Programming", "C Interview: Find Duplicates", "intermediate", 3, "1"),
    ("Data Structures", "Bloom Filter Concept", "advanced", 2, "1"),
    ("Data Structures", "LRU Cache Implementation", "advanced", 3, "1"),
    ("Data Structures", "Dynamic Programming Introduction", "intermediate", 4, "2"),
    ("Data Structures", "Memoization vs Tabulation", "intermediate", 4, "2"),
    ("Data Structures", "Fibonacci DP Approach", "intermediate", 4, "2"),
    ("Data Structures", "Longest Common Subsequence", "advanced", 3, "1"),
    ("Data Structures", "Knapsack Problem (0/1)", "advanced", 3, "1"),
    ("Data Structures", "Matrix Chain Multiplication", "advanced", 2, "1"),
    ("Data Structures", "Subset Sum Problem", "advanced", 2, "1"),
    ("OOP C++", "Initialization List in Constructor", "intermediate", 4, "2"),
    ("OOP C++", "Explicit Constructor", "intermediate", 3, "1"),
    ("OOP C++", "Move Semantics (C++11)", "advanced", 3, "1"),
    ("OOP C++", "Rvalue References", "advanced", 2, "1"),
    ("OOP C++", "Perfect Forwarding", "advanced", 2, "1"),
    ("OOP C++", "Rule of Three/Five/Zero", "advanced", 3, "1"),
    ("OOP C++", "RAII Idiom", "advanced", 3, "1"),
    ("OOP C++", "CRTP (Curiously Recurring Template)", "advanced", 2, "1"),
    ("Operating Systems", "Livlock vs Deadlock", "intermediate", 3, "1"),
    ("Operating Systems", "Mutual Exclusion Algorithms", "advanced", 3, "1"),
    ("Operating Systems", "Peterson's Algorithm", "advanced", 3, "1"),
    ("Operating Systems", "Test-and-Set Instruction", "advanced", 2, "1"),
    ("Operating Systems", "Readers-Writers: Reader Preferred", "advanced", 3, "1"),
    ("Operating Systems", "Readers-Writers: Writer Preferred", "advanced", 2, "1"),
    ("Operating Systems", "Single Point of Failure in Deadlock", "intermediate", 3, "1"),
    ("Networking", "CSMA/CD Protocol", "intermediate", 3, "1"),
    ("Networking", "CSMA/CA Protocol", "intermediate", 3, "1"),
    ("Networking", "Ethernet Frame Format", "advanced", 2, "1"),
    ("Networking", "Switching: Store & Forward", "intermediate", 3, "1"),
    ("Networking", "Switching: Cut Through", "intermediate", 2, "1"),
    ("Networking", "WAN Technologies", "beginner", 3, "1"),
    ("Networking", "SONET/SDH", "advanced", 2, "1"),
    ("Networking", "Access Control Methods", "intermediate", 3, "1"),
    ("Networking", "Framing in Data Link Layer", "intermediate", 3, "1"),
    ("DBMS", "TRUNCATE vs DELETE", "beginner", 4, "2"),
    ("DBMS", "SQL Injection & Prevention", "intermediate", 3, "1"),
    ("DBMS", "Database Normalization Examples", "intermediate", 4, "2"),
    ("DBMS", "ACID in Distributed Systems", "advanced", 3, "1"),
    ("Big Data & AI", "Bias-Variance Tradeoff", "advanced", 2, "1"),
    ("Big Data & AI", "Overfitting Prevention Techniques", "intermediate", 3, "1"),
    ("Big Data & AI", "Feature Selection Methods", "intermediate", 3, "1"),
    ("Big Data & AI", "Cross-Validation Techniques", "advanced", 2, "1"),
    ("Big Data & AI", "ROC Curve & AUC", "advanced", 2, "1"),
    ("Big Data & AI", "Clustering Metrics", "advanced", 2, "1"),
    ("Big Data & AI", "Dimensionality vs Sparsity", "intermediate", 3, "1"),
    ("Computer Fundamentals", "ASCII vs Unicode", "beginner", 4, "2"),
    ("Computer Fundamentals", "BCD (Binary Coded Decimal)", "beginner", 3, "1"),
    ("Computer Fundamentals", "Gray Code", "beginner", 3, "1"),
    ("Computer Fundamentals", "Excess-3 Code", "beginner", 2, "1"),
    ("Computer Fundamentals", "Hamming Code (Error Correction)", "intermediate", 3, "1"),
    ("Computer Fundamentals", "Parity Bit", "beginner", 3, "1"),
    ("Computer Fundamentals", "NOR as Universal Gate", "beginner", 3, "1"),
    ("Computer Fundamentals", "NAND as Universal Gate", "beginner", 3, "1"),
    ("Computer Fundamentals", "De Morgan's Theorems", "beginner", 4, "2"),
    ("Computer Fundamentals", "Karnaugh Map (K-Map)", "intermediate", 3, "1"),
    ("Computer Fundamentals", "Flip-Flop Types (SR, D, JK, T)", "intermediate", 3, "1"),
    ("Computer Fundamentals", "Multiplexer & Demultiplexer", "beginner", 3, "1"),
    ("Computer Fundamentals", "Encoder & Decoder", "beginner", 3, "1"),
]
for subj, t, d, i, e in extra3:
    add_bulk(subj, t, d, i, e)

print(f"After Extra batch 3: {len(cards)} cards")

# ===== FOURTH BATCH: Reach 1000+ =====
extra4 = [
    ("Quantitative Aptitude", "Remainder Theorem Applications", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Chinese Remainder Theorem", "advanced", 2, "1"),
    ("Quantitative Aptitude", "Factorial Trailing Zeros", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Consecutive Integer Problems", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Digit Sum Problems", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Palindrome Number Problems", "beginner", 2, "1"),
    ("Quantitative Aptitude", "Armstrong Number", "beginner", 2, "1"),
    ("Quantitative Aptitude", "Perfect Number", "beginner", 2, "1"),
    ("Quantitative Aptitude", "Prime Number Testing", "beginner", 3, "1"),
    ("Quantitative Aptitude", "Sieve of Eratosthenes", "intermediate", 2, "1"),
    ("English", "Article Usage Rules (a/an/the)", "beginner", 3, "1"),
    ("English", "Determiner Usage", "beginner", 3, "1"),
    ("English", "Quantifier (much/many/few/little)", "beginner", 3, "1"),
    ("English", "Subjunctive Mood", "advanced", 2, "1"),
    ("English", "Ellipsis & Substitution", "advanced", 2, "1"),
    ("English", "Coherence & Cohesion", "intermediate", 3, "1"),
    ("English", "Reference Words", "intermediate", 3, "1"),
    ("English", "Linking Words & Connectors", "beginner", 3, "1"),
    ("English", "Negative Prefixes (un-, dis-, in-)", "beginner", 3, "1"),
    ("English", "Word Root & Etymology", "intermediate", 2, "1"),
    ("Reasoning", "Direction Sense with Distance", "beginner", 4, "2"),
    ("Reasoning", "Clock-based Problems", "intermediate", 3, "1"),
    ("Reasoning", "Calendar-based Reasoning", "intermediate", 3, "1"),
    ("Reasoning", "Mathematical Inequalities", "intermediate", 3, "1"),
    ("Reasoning", "Puzzle with Two/Three Variables", "advanced", 4, "2"),
    ("Reasoning", "Input-Output: Shifting Pattern", "advanced", 3, "1"),
    ("Reasoning", "Input-Output: Mathematical Operation", "advanced", 3, "1"),
    ("Reasoning", "Syllogism: Possibility Cases", "advanced", 3, "1"),
    ("Reasoning", "Coded Inequalities", "intermediate", 3, "1"),
    ("Reasoning", "Order & Ranking with Conditions", "intermediate", 3, "1"),
    ("C Programming", "Pointer Arithmetic: Subtraction", "advanced", 4, "2"),
    ("C Programming", "Pointer Comparison", "intermediate", 3, "1"),
    ("C Programming", "Array Decay to Pointer", "intermediate", 4, "2"),
    ("C Programming", "String Literal vs Char Array", "intermediate", 3, "1"),
    ("C Programming", "Const Pointer vs Pointer to Const", "advanced", 3, "1"),
    ("C Programming", "Restrict Keyword", "advanced", 2, "1"),
    ("C Programming", "Volatile Keyword Use Cases", "advanced", 3, "1"),
    ("C Programming", "Structure Bit Fields in Memory", "advanced", 3, "1"),
    ("C Programming", "Union for Type Punning", "advanced", 2, "1"),
    ("C Programming", "Designated Initializers (C99)", "intermediate", 2, "1"),
    ("Data Structures", "Open Addressing: Linear Probing", "advanced", 3, "1"),
    ("Data Structures", "Open Addressing: Quadratic Probing", "advanced", 2, "1"),
    ("Data Structures", "Double Hashing", "advanced", 2, "1"),
    ("Data Structures", "Separate Chaining", "advanced", 3, "1"),
    ("Data Structures", "BST: Insert & Delete", "intermediate", 4, "2"),
    ("Data Structures", "BST: Search & Traversals", "intermediate", 4, "2"),
    ("Data Structures", "AVL: Insert with Rotations", "advanced", 3, "1"),
    ("Data Structures", "Red-Black Tree Properties", "advanced", 2, "1"),
    ("Data Structures", "Hash Table Load Factor", "intermediate", 3, "1"),
    ("Data Structures", "Rehashing", "advanced", 2, "1"),
    ("OOP C++", "Delegating Constructors (C++11)", "advanced", 2, "1"),
    ("OOP C++", "Inheriting Constructors", "advanced", 2, "1"),
    ("OOP C++", "Override & Final Keywords", "advanced", 3, "1"),
    ("OOP C++", "Default & Delete Functions", "advanced", 3, "1"),
    ("OOP C++", "Noexcept Specifier", "advanced", 2, "1"),
    ("OOP C++", "Constexpr & Consteval", "advanced", 2, "1"),
    ("OOP C++", "Structured Bindings (C++17)", "advanced", 2, "1"),
    ("OOP C++", "std::vector Deep Dive", "intermediate", 3, "1"),
    ("OOP C++", "std::map vs std::unordered_map", "intermediate", 3, "1"),
    ("OOP C++", "Iterator Invalidation", "advanced", 2, "1"),
    ("Operating Systems", "Process Tree Structure", "intermediate", 3, "1"),
    ("Operating Systems", "Orphan vs Zombie Process", "intermediate", 4, "2"),
    ("Operating Systems", "Wait System Call", "intermediate", 3, "1"),
    ("Operating Systems", "Exec System Call Family", "intermediate", 3, "1"),
    ("Operating Systems", "Process Control: fork() Return", "intermediate", 4, "2"),
    ("Operating Systems", "Memory-Mapped Files", "advanced", 2, "1"),
    ("Operating Systems", "Demand Paging: Page Fault Rate", "intermediate", 3, "1"),
    ("Operating Systems", "Page Replacement: Clock Algorithm", "advanced", 3, "1"),
    ("Operating Systems", "Page Replacement: Second Chance", "advanced", 3, "1"),
    ("Operating Systems", "Working Set Model", "advanced", 2, "1"),
    ("Networking", "Flow Control: Stop-and-Wait", "intermediate", 3, "1"),
    ("Networking", "Flow Control: Go-Back-N", "advanced", 3, "1"),
    ("Networking", "Flow Control: Selective Repeat", "advanced", 2, "1"),
    ("Networking", "Error Correction: Hamming Code", "advanced", 2, "1"),
    ("Networking", "Error Detection: Checksum Method", "intermediate", 3, "1"),
    ("Networking", "Error Detection: CRC Polynomial", "advanced", 2, "1"),
    ("Networking", "IPv4 Fragmentation", "advanced", 3, "1"),
    ("Networking", "IPv6 Address Types", "intermediate", 3, "1"),
    ("Networking", "Multicast Routing", "advanced", 2, "1"),
    ("Networking", "Unicast Routing Protocols", "intermediate", 3, "1"),
    ("DBMS", "GROUP BY with Multiple Columns", "intermediate", 3, "1"),
    ("DBMS", "Nested Aggregate Queries", "advanced", 3, "1"),
    ("DBMS", "CASE Expression in SQL", "intermediate", 3, "1"),
    ("DBMS", "COALESCE & NULLIF Functions", "intermediate", 3, "1"),
    ("DBMS", "Natural Join vs Inner Join", "intermediate", 3, "1"),
    ("DBMS", "Self Join Use Cases", "intermediate", 3, "1"),
    ("DBMS", "Recursive CTE (Common Table Expr)", "advanced", 2, "1"),
    ("DBMS", "Pivoting Data in SQL", "advanced", 2, "1"),
    ("DBMS", "String Functions in SQL", "beginner", 3, "1"),
    ("DBMS", "Date/Time Functions in SQL", "beginner", 3, "1"),
    ("Big Data & AI", "Batch vs Mini-batch Gradient Desc", "advanced", 2, "1"),
    ("Big Data & AI", "Stochastic Gradient Descent", "advanced", 2, "1"),
    ("Big Data & AI", "Learning Rate Scheduling", "advanced", 2, "1"),
    ("Big Data & AI", "Batch Normalization", "advanced", 2, "1"),
    ("Big Data & AI", "Dropout Regularization", "advanced", 2, "1"),
    ("Big Data & AI", "Data Augmentation Techniques", "intermediate", 3, "1"),
    ("Big Data & AI", "TF-IDF Vectorization", "intermediate", 3, "1"),
    ("Big Data & AI", "Sentiment Analysis Pipeline", "intermediate", 3, "1"),
    ("Big Data & AI", "Image Classification Pipeline", "intermediate", 3, "1"),
    ("Big Data & AI", "Recommendation Systems", "beginner", 3, "1"),
]
for subj, t, d, i, e in extra4:
    add_bulk(subj, t, d, i, e)

print(f"After Extra batch 4: {len(cards)} cards")

# ===== FIFTH BATCH: Final push to 1000+ =====
extra5 = [
    ("Quantitative Aptitude", "Euclid's Division Lemma", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "LCM x HCF for Three Numbers Myth", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Sum of AP Series", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Sum of GP Series", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Harmonic Progression", "advanced", 2, "1"),
    ("Quantitative Aptitude", "Special Numbers (Automorphic)", "beginner", 2, "1"),
    ("English", "Synonym Precision (subtle diff)", "intermediate", 4, "2"),
    ("English", "Antonym Direction (gradable)", "intermediate", 3, "1"),
    ("English", "Reading Speed Techniques", "beginner", 4, "2"),
    ("English", "Inference vs Assumption", "intermediate", 3, "1"),
    ("Reasoning", "Cube Painting Problems", "advanced", 3, "1"),
    ("Reasoning", "Dice: Opposite Faces", "beginner", 3, "1"),
    ("Reasoning", " Cube & Dice Combined", "intermediate", 3, "1"),
    ("Reasoning", "Figure Completion", "intermediate", 3, "1"),
    ("C Programming", "qsort() & bsearch() Library", "intermediate", 3, "1"),
    ("C Programming", "Memory Alignment & Padding Rules", "advanced", 3, "1"),
    ("C Programming", "Static Keyword: Block Scope", "intermediate", 4, "2"),
    ("C Programming", "Extern: Multiple Files", "intermediate", 3, "1"),
    ("Data Structures", "Stack vs Heap Allocation Speed", "intermediate", 3, "1"),
    ("Data Structures", "Queue vs Deque Performance", "intermediate", 3, "1"),
    ("OOP C++", "Object Size & Padding", "advanced", 3, "1"),
    ("OOP C++", "Empty Class Size in C++", "intermediate", 3, "1"),
    ("Operating Systems", "Process vs Thread Overhead", "intermediate", 4, "2"),
    ("Operating Systems", "Virtual Memory & Performance", "intermediate", 3, "1"),
    ("Networking", "Bandwidth vs Throughput", "beginner", 4, "2"),
    ("Networking", "Latency vs Jitter", "beginner", 3, "1"),
    ("DBMS", "Dense vs Sparse Index", "intermediate", 3, "1"),
    ("DBMS", "Primary vs Secondary Index", "intermediate", 3, "1"),
    ("Big Data & AI", "Supervised vs Unsupervised Use Cases", "beginner", 4, "2"),
    ("Big Data & AI", "Classification vs Regression", "beginner", 4, "2"),
    ("Computer Fundamentals", "Full Adder & Half Adder", "beginner", 3, "1"),
    ("Computer Fundamentals", "Ripple Carry Adder", "intermediate", 2, "1"),
    ("Computer Fundamentals", "Multiplexer as Function Generator", "advanced", 2, "1"),
    ("Quantitative Aptitude", "Cistern: Two Pipes + Leak", "intermediate", 3, "1"),
    ("Quantitative Aptitude", "Work: Men & Days Inverse", "beginner", 3, "1"),
    ("C Programming", "String Palindrome Check Code", "beginner", 4, "2"),
    ("C Programming", "Array Rotation Algorithms", "intermediate", 3, "1"),
    ("Operating Systems", "Process State Transition Diagram", "intermediate", 4, "2"),
    ("Networking", "OSI Layer Mnemonic Memory", "beginner", 5, "3"),
    ("DBMS", "ACID: Each Property Example", "intermediate", 4, "2"),
    ("Data Structures", "Array vs Linked List Comparison", "beginner", 4, "2"),
    ("OOP C++", "Encapsulation Real Example", "beginner", 4, "2"),
    ("Quantitative Aptitude", "Profit/Loss: Multiple Items", "intermediate", 4, "2"),
    ("English", "Word Pair Relationships", "intermediate", 3, "1"),
    ("Reasoning", "Pattern in Number Matrix", "intermediate", 3, "1"),
    ("Big Data & AI", "HDFS: Block Size & Replication", "beginner", 3, "1"),
    ("Big Data & AI", "MapReduce: Mapper & Reducer", "intermediate", 3, "1"),
    ("Computer Fundamentals", "NAND Gate Universal Property Proof", "beginner", 3, "1"),
    ("Networking", "Subnetting: Finding Network ID", "advanced", 3, "1"),
    ("Quantitative Aptitude", "Compound Interest vs Simple Interest Diff", "beginner", 4, "2"),
    ("C Programming", "Floyd's Triangle Printing", "beginner", 3, "1"),
    ("Data Structures", "Reverse Linked List: Iterative", "intermediate", 4, "2"),
    ("OOP C++", "Polymorphism: Real-life Analogy", "beginner", 4, "2"),
]
for subj, t, d, i, e in extra5:
    add_bulk(subj, t, d, i, e)

print(f"FINAL TOTAL: {len(cards)} cards")

# Save as JSON
with open('src/data/topicCards/cards.json', 'w') as f:
    json.dump(cards, f, ensure_ascii=False, indent=2)

print(f"\nSaved {len(cards)} cards to src/data/topicCards/cards.json")
print(f"File size: {len(json.dumps(cards, ensure_ascii=False))} bytes")

# Print subject distribution
dist = Counter(c['subject'] for c in cards)
print("\nSubject distribution:")
for subj, count in dist.most_common():
    print(f"  {subj}: {count}")
